[Income]
Salary = 0
Allowance = 0
Bonus = 0
Misc = 0
Pension = 0

[Income.Overtime]
"1.5" = 0
"2.0" = 0
"2.5" = 0

[Expenses]
Mortgage = 0
Council_Tax = 0
Credit_Cards = 0
Internet = 0
Electicity = 0
Water = 0
Subscriptions = 0
Savings = 0
Investments = 0

[Tax]
Year = 2025 # Tax year (e.g. "2025" for the 2025/26 tax year)
# Personal_Allowance = 12570 # This can be uncommented to override the default personal allowance (in pounds)